### ISSUE TITLE
Error on compile

### ISSUE THREAD

**Issue by plagache** [sioodmy/dwm#1]
Hi,

Your config.h is including shiftview.c,
but there is no file with this name in the repo.
What am I missing ?
Thank you.

**Comment by pierre-rs** [comment]
+1

```
config.h:111:10: fatal error: shiftview.c: No such file or directory
  111 | #include "shiftview.c"
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:18: dwm.o] Error 1
```

Ubuntu 20.04.3 LTS

**Comment by 0xff01WasTaken** [comment]
same problem here

**Comment by 0xff01WasTaken** [comment]
temporary fix is to comment out #include "shiftview.c" in config.h at 111

( /* #include shiftview.c" */)

**Comment by sioodmy** [comment]
fixed, by including shiftview.c in repo
